Test file

In [2]:
from IPython.display import display, Math, Latex

import pandas as pd
import numpy as np
import numpy_financial as npf
import yfinance as yf
import matplotlib.pyplot as plt
import random
from datetime import datetime
import itertools # Library for creating and using "Iterators" on multiple python types.

In [22]:
ticker_file = pd.read_csv('Tickers_Example.csv', header=None)
ticker_file.rename(columns={0: 'name'}, inplace=True)
msft = {'name': ['MSFT']}
msft_df = pd.DataFrame(msft)
pd.concat([ticker_file, msft_df], ignore_index=True)
#df = pd.concat([pd.DataFrame([[1,2]], columns=df.columns), df], ignore_index=True)

       name
0      AAPL
1      ABBV
2       ABT
3       ACN
4       AGN
5       AIG
6      AMZN
7       AXP
8        BA
9       BAC
10    BB.TO
11     BIIB
12       BK
13      BLK
14      BMY
15        C
16      CAT
17     CELG
18       CL
19       KO
20      LLY
21      LMT
22       MO
23      MON
24      MRK
25      PEP
26      PFE
27       PG
28       PM
29     PYPL
30     QCOM
31      RTN
32    RY.TO
33  SHOP.TO
34     T.TO
35    TD.TO
36      TXN
37      UNH
38      UNP
39      UPS
40      USB
41     MSFT

In [32]:
portfolio = pd.DataFrame()
new_row = {'name': "shop.to", 'weight': 15, 'shares': 1000, 'price': 140, 'transaction_fees': 0.90, 'spent': 140000}
new_row_df = pd.DataFrame(new_row, index=[0])
portfolio = pd.concat([portfolio, new_row_df], ignore_index=True)

new_row_2 = {'name': "td.to", 'weight': 5, 'shares': 20, 'price': 70, 'transaction_fees': 3.95, 'spent': 1400}
new_row_df_2 = pd.DataFrame(new_row_2, index=[0])
portfolio = pd.concat([portfolio, new_row_df_2], ignore_index=True)

portfolio

      name  weight  shares  price  transaction_fees   spent
0  shop.to      15    1000    140              0.90  140000
1    td.to       5      20     70              3.95    1400